//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargasDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal Id_usuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
        public string Email { get; set; }
        public string Pregunta_seguridad { get; set; }
        public string Respuesta_seguridad { get; set; }
    }
}
